theme: jekyll-theme-cayman
title: Take Action for Open
description: A Librarian Toolkit for Participating in OA Week 2017
url: https://sparcopen.github.io/OA-Week-Toolkit/
language: en_US
show_downloads: true
gems:
  - jekyll-seo-tag
